name: describe-cloudformation-stack
on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      cloudformation-stack-name:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
    outputs:
      terraform-execution-role-arn:
        value: ${{ jobs.describe-cloudformation-stack.outputs.terraform-execution-role-arn }}
      terraform-state-bucket-name:
        value: ${{ jobs.describe-cloudformation-stack.outputs.terraform-state-bucket-name }}
      terraform-state-lock-table-name:
        value: ${{ jobs.describe-cloudformation-stack.outputs.terraform-state-lock-table-name }}
jobs:
  describe-cloudformation-stack:
    name: Describe CloudFormation stack
    runs-on: ubuntu-latest
    outputs:
      terraform-execution-role-arn: ${{ steps.describe-cloudformation-stack.outputs.terraform-execution-role-arn }}
      terraform-state-bucket-name: ${{ steps.describe-cloudformation-stack.outputs.terraform-state-bucket-name }}
      terraform-state-lock-table-name: ${{ steps.describe-cloudformation-stack.outputs.terraform-state-lock-table-name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup CloudFormation environment
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-region: ${{ inputs.aws-region }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
      - name: Describe CloudFormation stack
        id: describe-cloudformation-stack
        run: |
          STACK_OUTPUT=$(
            aws cloudformation describe-stacks \
            --stack-name ${{ inputs.cloudformation-stack-name }} \
            --query "Stacks[0].Outputs" \
            --output json
          )
          TERRAFORM_EXECUTION_ROLE_ARN=$(echo "$STACK_OUTPUT" | jq -r '.[] | select(.OutputKey=="TerraformExecutionRoleArn") | .OutputValue')
          TERRAFORM_STATE_BUCKET_NAME=$(echo "$STACK_OUTPUT" | jq -r '.[] | select(.OutputKey=="TerraformStateBucketName") | .OutputValue')
          TERRAFORM_STATE_LOCK_TABLE_NAME=$(echo "$STACK_OUTPUT" | jq -r '.[] | select(.OutputKey=="TerraformStateLockTableName") | .OutputValue')
        
          echo "terraform-execution-role-arn=$TERRAFORM_EXECUTION_ROLE_ARN" >> $GITHUB_OUTPUT
          echo "terraform-state-bucket-name=$TERRAFORM_STATE_BUCKET_NAME" >> $GITHUB_OUTPUT
          echo "terraform-state-lock-table-name=$TERRAFORM_STATE_LOCK_TABLE_NAME" >> $GITHUB_OUTPUT
