name: describe-cloudformation-stack-on-dispatch
on:
  workflow_dispatch:
jobs:
  describe-cloudformation-stack:
    name: Describe CloudFormation stack
    uses: ./.github/workflows/describe-cloudformation-stack.yml
    with:
      aws-region: ${{ vars.AWS_REGION }}
      cloudformation-stack-name: ${{ vars.CLOUDFORMATION_STACK_NAME }}
    secrets:
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  echo-outputs:
    name: Echo CloudFormation stack outputs
    runs-on: ubuntu-latest
    steps:
      - name: Echo outputs
        run: |
          echo "terraform-execution-role-arn=${{ needs.describe-cloudformation-stack.outputs.terraform-execution-role-arn }}
          echo "terraform-state-bucket-name=${{ needs.describe-cloudformation-stack.outputs.terraform-state-bucket-name }}
          echo "terraform-state-lock-table-name=${{ needs.describe-cloudformation-stack.outputs.terraform-state-lock-table-name }}
