name: describe-cloudformation-stack-on-dispatch
on:
  workflow_dispatch:
jobs:
  describe-cloudformation-stack:
    name: Describe CloudFormation stack
    uses: ./.github/workflows/describe-cloudformation-stack.yml
    with:
      aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
      aws-region: ${{ vars.AWS_REGION }}
      aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
      cloudformation-stack-name: ${{ vars.CLOUDFORMATION_STACK_NAME }}
