name: on-merge-master
on:
  push:
    branches:
      - "master"
jobs:
  run-cloudformation-deploy:
    name: Run Cloudformation deploy
    uses: ./.github/workflows/run-cloudformation-deploy.yml
    with:
      aws-region: ${{ vars.AWS_REGION }}
      cloudformation-stack-name: ${{ vars.CLOUDFORMATION_STACK_NAME }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  describe-cloudformation-stack:
    name: Describe CloudFormation stack
    needs: run-cloudformation-deploy
    uses: ./.github/workflows/describe-cloudformation-stack.yml
    with:
      aws-region: ${{ vars.AWS_REGION }}
      cloudformation-stack-name: ${{ vars.CLOUDFORMATION_STACK_NAME }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  run-terraform-apply:
    name: Run Terraform apply
    needs: describe-cloudformation-stack
    uses: ./.github/workflows/run-terraform-command.yml
    with:
      terraform-execution-role-arn: ${{ needs.describe-cloudformation-stack.outputs.terraform-execution-role-arn }}
      terraform-command: terraform apply -auto-approve
      aws-region: ${{ vars.AWS_REGION }}
      terraform-state-bucket-name: ${{ needs.describe-cloudformation-stack.outputs.terraform-state-bucket-name }}
      terraform-state-lock-table-name: ${{ needs.describe-cloudformation-stack.outputs.terraform-state-lock-table-name }}
