name: preview-cloudformation-change-set-on-pull-request
on:
  pull_request:
    paths:
      - "cloudformation-templates/*.yaml"
      - "cloudformation-templates/*.yml"
      - ".github/workflows/preview-cloudformation-change-set-on-pull-request.yml"
jobs:
  preview-cloudformation-change-set:
    name: Preview CloudFormation change set
    uses: ./.github/workflows/preview-cloudformation-change-set.yml
    with:
      cloudformation-change-set-name: changeset-${{ github.sha }}
      cloudformation-stack-name: ${{ vars.CLOUDFORMATION_STACK_NAME }}
      aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ vars.AWS_REGION }}
