name: preview-cloudformation-change-set
on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      cloudformation-stack-name:
        required: true
        type: string
      cloudformation-change-set-name:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
jobs:
  preview-cloudformation-change-set:
    name: Preview CloudFormation change set
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup CloudFormation environment
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-region: ${{ inputs.aws-region }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
      - name: Get repository name and owner
        id: get-repository-name-and-owner
        uses: ./.github/actions/get-repository-name-and-owner
      - name: Create CloudFormation change set
        run: |
          aws cloudformation create-change-set \
            --template-body file://cloudformation-templates/main.yml \
            --stack-name ${{ inputs.cloudformation-stack-name }} \
            --change-set-name ${{ inputs.cloudformation-change-set-name }} \
            --change-set-type UPDATE \
            --parameters \ 
              ParameterKey=RepositoryName,ParameterValue=${{ steps.get-repository-name-and-owner.outputs.repository-name }} \
              ParameterKey=RepositoryOwner,ParameterValue=${{ steps.get-repository-name-and-owner.outputs.repository-owner }}
      - name: Wait for CloudFormation change set creation
        run: |
          aws cloudformation wait change-set-create-complete \
            --stack-name ${{ inputs.cloudformation-stack-name }} \
            --change-set-name ${{ inputs.cloudformation-change-set-name }}
      - name: Preview CloudFormation change set
        run: |
          aws cloudformation describe-change-set \
            --stack-name ${{ inputs.cloudformation-stack-name }} \
            --change-set-name ${{ inputs.cloudformation-change-set-name }}
      - name: Delete CloudFormation change set
        if: always() # Ensures this runs even if the previous step fails
        run: |
          aws cloudformation delete-change-set \
            --stack-name ${{ inputs.cloudformation-stack-name }}  \
            --change-set-name ${{ inputs.cloudformation-change-set-name }}
