name: run-terraform-command
on:
  workflow_call:
    inputs:
      terraform-execution-role-arn:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      terraform-command:
        required: true
        type: string
jobs:
  run-terraform-command:
    name: Run Terraform command
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ inputs.terraform-execution-role-arn }}
          aws-region: ${{ inputs.aws-region }}
      - name: Run Terraform command
        uses: ./.github/actions/setup-terraform-environment-and-run-command
        with:
          aws-region: ${{ inputs.aws-region }}
          terraform-execution-role-arn: ${{ inputs.terraform-execution-role-arn }}
          terraform-directory: ./terraform
          terraform-command: ${{ inputs.terraform-command }}
