name: run-cloudformation-delete-stack-on-dispatch
on:
  workflow_dispatch:
jobs:
  run-cloudformation-delete-stack:
    name: Run CloudFormation delete stack
    uses: ./.github/workflows/run-cloudformation-delete-stack.yml
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-region: ${{ vars.AWS_REGION }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      cloudformation-stack-name: ${{ vars.CLOUDFORMATION_STACK_NAME }}
