name: run-cloudformation-deploy-on-dispatch
on:
  workflow_dispatch:
jobs:
  run-cloudformation-deploy:
    name: Run CloudFormation deploy
    uses: ./.github/workflows/run-cloudformation-deploy.yml
    with:
      aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
      aws-region: ${{ vars.AWS_REGION }}
      aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
      cloudformation-stack-name: ${{ vars.CLOUDFORMATION_STACK_NAME }}
