name: run-cloudformation-deploy-on-merge-master
on:
  push:
    branches:
      - "master"
jobs:
  deploy:
    name: Deploy CloudFormation template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Deploy templates
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ vars.CLOUDFORMATION_STACK_NAME }}
          template: cloudformation-templates/main.yml
          tags: |
            repo=${{ github.repository }}
