name: validate-cloudformation-templates-on-pull-request
on:
  pull_request:
    paths:
      - "cloudformation-templates/*.yaml"
      - "cloudformation-templates/*.yml"
      - ".github/workflows/validate-cloudformation-templates-on-pull-request.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  validate-cloudformation-templates:
    name: Validate CloudFormation templates
    uses: ./.github/workflows/validate-cloudformation-templates.yml
    with:
      aws-region: ${{ vars.AWS_REGION }}
      aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ vars.AWS_SECRET_ACCESS_KEY }}
