name: validate-cloudformation-templates-on-pull-request
on:
  pull_request:
    paths:
      - "cloudformation-templates/*.yaml"
      - "cloudformation-templates/*.yml"
      - ".github/workflows/validate-cloudformation-templates-on-pull-request.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
env:
  AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ vars.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.AWS_REGION }}
jobs:
  validate-cloudformation-templates:
    name: Validate CloudFormation templates
    uses: ./.github/workflows/reusable/validate-cloudformation-templates.yml
    with:
      aws-region: ${{ env.AWS_REGION }}
      aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
