name: validate-terraform
on:
  workflow_call:
jobs:
  validate-terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Check Terraform formatting
        run: terraform fmt -recursive -check -diff
        working-directory: ./terraform
      - name: Initialise Terraform (without a backend)
        run: terraform init -backend=false
        working-directory: ./terraform
      - name: Validate Terraform configuration
        run: terraform validate
        working-directory: ./terraform
