name: validate-cloudformation-templates
on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
jobs:
  validate-cloudformation-templates:
    name: Validate CloudFormation templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate CloudFormation templates
        uses: ./.github/actions/configure-aws-cli-and-run-command
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-region: ${{ inputs.aws-region }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          command: |
            aws cloudformation validate-template \
              --template-body file://cloudformation-templates/main.yml
